name: Build Linux Binary from Public External Repo with CMake and Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout public external repository
        uses: actions/checkout@v3
        # env:
        #   GITHUB_REPOSITORY: "ScanTailor-Advanced/scantailor-advanced"
        with:
          repository: "ScanTailor-Advanced/scantailor-advanced"
          ref: ${{ github.ref }}
          # token: ${{ env.GH_PAT }}
          path: scantailor-advanced

      - name: Set up CMake, GCC and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev qtbase5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools python3-dev autotools-dev libicu-dev

      - uses: rui314/setup-mold@v1
        name: Set up Mold linker

      - name: Build
        run: |
          cd scantailor-advanced
          mkdir dist
          mkdir build && cd build
          export LDFLAGS="-L/usr/local/lib,--rpath=/usr/local/lib"
          export LD_LIBRARY_PATH="/usr/local/lib"
          cmake -G "Unix Makefiles" ..
          make -j$(nproc)
          make DESTDIR="../dist" install

      - name: Compress binary
        run: |
          cd scantailor-advanced/dist
          tar czvf scantailor-advanced-bin.tar.gz ./usr

      # - name: Create GitHub Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   # env:
      #   #   GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      #     replace_artifacts: true
      #     allow_updates: true
      # - name: Upload binary as release asset
      #   uses: actions/upload-release-asset@v1
      #   # env:
      #   #   GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: scantailor-advanced-bin.tar.gz
      #     asset_name: scantailor-advanced-bin.tar.gz
      #     asset_content_type: application/gzip
      - name: Release
        # run: |
        #   ls -a
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          files: scantailor-advanced/dist/scantailor-advanced-bin.tar.gz
          name: Release ${{ github.ref }}
          draft: true
